// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iwqkfpgforhqjxnhppih.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml3cWtmcGdmb3JocWp4bmhwcGloIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwNDkyNjQsImV4cCI6MjA3NDYyNTI2NH0.zNBp_rU76Yklo3q_JTfjj4bGgYNarYeOlkp0AhNM-us";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});